spring.application.name=ms-administracion-archivos
server.port=8080

# Azure AD B2C
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWK_SET_URI}
spring.security.oauth2.client.registration.azure.client-id=${CLIENT_ID}

# AWS S3
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME}

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

# Configuracion EFS
efs.path=${EFS_PATH:/app/efs}
